apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  type: LoadBalancer # LoadBalancer에서 ClusterIP로 변경
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-boot-app
