name: Terraform Backend Setup

on:
  workflow_dispatch:  # 수동 트리거만 허용

jobs:
  setup-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 백엔드 리소스만 생성
      - name: Initialize Terraform
        run: cd terraform_backend_setup && terraform init 

      - name: Create backend resources
        run: |
          cd terraform_backend_setup
          terraform apply -auto-approve

      # 이 워크플로우를 실행하면 이제 백엔드 리소스가 생성되었습니다!