name: Terraform Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 여기서는 S3 버킷이 이미 존재한다고 가정합니다
      - name: Initialize Terraform with S3 Backend
        run: cd terraform && terraform init -migrate-state

      - name: Terraform Plan
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="region=${{ secrets.AWS_REGION }}" \
            -var="cluster_name=${{ secrets.EKS_CLUSTER_NAME }}" \
            -var="ecr_repository_name=${{ secrets.ECR_REPOSITORY }}" \
            -var="acm_certificate_arn=${{ secrets.ACM_CERTIFICATE_ARN }}" \
            -var="domain_name=${{ secrets.DOMAIN_NAME }}" \
            -var="hosted_zone_name=${{ secrets.HOSTED_ZONE_NAME }}" \
            -out=tfplan
          
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan